# Etapa de build
FROM golang:1.23-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o app

# Etapa de runtime
FROM alpine:latest

WORKDIR /root/
COPY --from=builder /app/app .
COPY movies.csv .

CMD ["./app"]
